add_raisonvisite:
    path:     /ajouter
    defaults: { _controller: SecurityUserBundle:RaisonVisite:add }

edit_raisonvisite:
    path: /modifier/{id}
    defaults: { _controller: SecurityUserBundle:RaisonVisite:edit }

show_raisonvisite:
    path: /
    defaults: { _controller: SecurityUserBundle:RaisonVisite:show }

delete_raisonvisite:
    path: /supprimer/{id}
    defaults: { _controller: SecurityUserBundle:RaisonVisite:delete }