back:
    resource: "@BackBundle/Resources/config/routing.yml"
    prefix:   /admin/

front:
    resource: "@FrontBundle/Resources/config/routing.yml"
    prefix:   /

security_user:
    resource: "@SecurityUserBundle/Resources/config/routing.yml"
    prefix:   /admin/

 
 
# app/config/routing.yml
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    
main:
    resource: "@MainBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

# app/config/routing.yml
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"